[package]
name = "sandboxed-regexp"
version = "0.2.0"
authors = ["Ryan Kelly <ryan@rfk.id.au>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/rfk/sandboxed-regexp"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen="0.2"
regex="1.3.4"
once_cell="1.3.1"
